#!/bin/sh

source "$(git --exec-path)/git-sh-setup"

USAGE=""

function _update_submodules() {
    if [[ $# == 0 ]]; then
		git submodule update --init --recursive --remote
		git submodule foreach --recursive "git checkout master; git pull"
    else
        usage
    fi  
}

_update_submodules ${@}
